In [3]:
import numpy as np

In [5]:
my_first_array = np.array([1, 2, 3,4,5])
my_first_array

array([1, 2, 3, 4, 5])

In [7]:
def cal_pop_fitness(equation_inputs, pop):
    # Calculating the fitness value of each solution in the current population.
    # The fitness function calulates the sum of products between each input and its corresponding weight.
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness




In [9]:
# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = len(equation_inputs)

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""
sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.
#Creating the initial population.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

"""
new_population[0, :] = [2.4,  0.7, 8, -2,   5,   1.1]
new_population[1, :] = [-0.4, 2.7, 5, -1,   7,   0.1]
new_population[2, :] = [-1,   2,   2, -3,   2,   0.9]
new_population[3, :] = [4,    7,   12, 6.1, 1.4, -4]
new_population[4, :] = [3.1,  4,   0,  2.4, 4.8,  0]
new_population[5, :] = [-2,   3,   -7, 6,   3,    3]
"""

best_outputs = []
num_generations = 1000
for generation in range(num_generations):
    print("Generation : ", generation)
    # Measuring the fitness of each chromosome in the population.
    fitness = cal_pop_fitness(equation_inputs, new_population)
    print("Fitness")
    print(fitness)


[[-0.45321113 -1.73799743 -2.33132104 -2.06117819  1.34143293 -1.61589773]
 [-3.7458764   0.70478562  0.15512362 -3.92973913 -1.27450155  2.83024853]
 [-1.21586676  1.99427463 -2.70478324 -1.43498091  1.1734313  -1.90720511]
 [-2.11259341  1.19838661 -2.89388886 -1.03786386 -0.37194162  2.24794858]
 [ 2.55591092  1.4368363   2.94799091 -1.5482255  -0.9158649   0.96548535]
 [-1.00181981  0.7452437  -3.07865158 -2.58891911 -2.73907548 -1.52878575]
 [-2.82980678  0.68260691  3.39921644  2.1382966   1.02913417  1.12494445]
 [ 2.77348115 -1.28452293 -0.12331242  2.98319502  3.78854998 -3.58751794]]
Generation :  0
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  1
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  2
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Genera

[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  357
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  358
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  359
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  360
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  361
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  362
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  363
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   

Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  857
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  858
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  859
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  860
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  861
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  862
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.46354455
   8.09748063  -6.70341522   3.33463661]
Generation :  863
Fitness
[-23.96340713 -34.78149083 -29.43754249 -32.63907766  15.4635